### ISSUE TITLE
Make it easier on the user to contribute their files.

### ISSUE THREAD

**Issue by pbogut** [bcook254/apex-legends-cache#7]
I was thinking about that before, even started some prototype but then scratched it.

Could we do an automation for that? I have 2 ideas in mind.

One idea is to make merging server, allow to upload cache file, merge it on the server and create PR. That requires server but it would be pain-free for the users.

```
cache-upload ~/Path/To/SteamLibrary
```

Another one could be creating script that will automate it locally. You would point it to steam library and if merg tool is installed (or could be included, as git submodule perhaps, or directly?) it would merge it. You would still have to make PR manually (unless we use `hub` then that part could be automated as well).

Second script to download newest file from the server, it could download it or use current git copy and merge it with your local cache.

What I was worried about was that someone could intentionally break cache file somehow, but if we use github for that, than PR has to be merged by human, so the risk is much lower.

It's just food for thoughts, maybe someone has better suggestions how this could be done?

**Comment by deep2p4ce** [comment]
I feel like the second option is easier to pull off. Mainly because one wouldn't need to make/pay or whatever a server and everything can be managed over github and script files. But it would also require a GitHub account.
For reference: I just did the whole process for contributing cache files for the very first time without prior knowledge about git-lfs, forking and pull request. I have prior experience with git but mainly with my own private projects on my local gitea server. I'm also new to linux gaming and switched when I read Apex could finally be played on linux. Thus I feel like for people new to Linux gaming (or Linux in general) one or two scripts for that automate the whole process of contributing cache files would be great. I would offer my help but I have limited experience with programming but I'm eager to learn.

**Comment by bcook254** [comment]
Thank you for your input.

I agree this isn't the easiest option for everyone to use, or does require quite a bit of manual work on both ends. When the reddit thread is used people can just send a link to this file and day here you go! But there was no real confirmation/transparency to whose files were merged and what the resulting files would look like. This isn't necessarily bad but does have some flaws I foresee as pointed out in the readme.

I imagine we could do something similar to that using GitHub issues with a template of sorts instead of requiring a PR, though those would be preferred still. One issue I thought I had figured out but turns out isn't perfect is when a PR is submitted but they didn't merge the latest cache file. For now I just manually merge the two and close the PR. But I would like to be able to do the merging process directly in the pull request to be a little more clear about where a change came from. More testing must be done here.

Finally, a script to automate merging cache files may not work as people can install the game in different locations and sometimes not even the default steam library path they have set (which is what I have done for example). If that can be figured out I'm more than happy to look at the solution and include that in this project.

**Comment by bcook254** [comment]
Really all I was trying to say is, is this this repo the perfect option? Absolutely not, but I personally believe a forum thread isn't the right solution either. This repository feels like a step towards the final perfect solution and will work until I or someone else can come up with something better.

**Comment by deep2p4ce** [comment]
I definitely think this repo is a step up from the reddit post and better solution. Also it's easier to version manage in case something goes wrong with a new cache merge. If you or anyone else can figure out how to get the auto merging to work after a pull request has been send, then this repo will constantly be up to date and not dependent on a single person to update the cache files. Regarding this matter, I guess you are using GitHub Actions, right? Also as was mentioned in the initial post, I think it might be a good idea to integrate/include the shader merging tool into this repo. Either as prebuild version or like a submodule. It might come in handy for future automation/scripting. Anyways thank you for creating this repo!

**Comment by bcook254** [comment]
> personally, I think creating a simple `merge.sh`script that automatically downloads the `dxvk-cache-tool`, copies the cache file from the default location and does the merge, woud probably suffice for the most part. You could add a custom steam libray to the arguments if you want to, that wouldn't be difficult.
>
> As for making it really simple for every one, yeah that would have to be done with a website or someting but I doubt its worth the effort.
> 
> Realistically, these cache files will only change with every major map change, which means a couple of days of collecting cached shades from a few hard core linux nerds like us until we have a more or less complete collection.
> 
> From then on people can just download the finished product and not worry about contributing.

I agree, the cache files are only updated on map changes which happens around 2 times a season. There will be a flurry of activity for the first couple of days afterwards and then it dies down. I will be thinking of a better overall solution such as a website, but for the time being we just need a few brave souls to get the big updates out of the way and then most people will have playable experiences and contribute small little cache file updates.

**Comment by bcook254** [comment]
As of today I have updated the README to more clearly show that opening an issue and attaching a linked file is the _preferred_ method of submission. This seems like the easiest option without creating anything from scratch at this point.

**Comment by pbogut** [comment]
For what is worth I started using `DXVK_ASYNC=1` with Proton-GE, and there is no need for cache files at all.
